CREATE ALIAS IF NOT EXISTS FT_INIT FOR "org.h2.fulltext.FullText.init";
CALL FT_INIT();
CALL FT_CREATE_INDEX('PUBLIC', 'LOGBACK_EVENT_MESSAGES', 'LOG_MESSAGE');
CALL FT_CREATE_INDEX('PUBLIC', 'LOGBACK_EVENT', 'LOG_MESSAGE');
