/* Copyright (c) 2018, EL.CO. SRL.  All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following
 * disclaimer in the documentation and/or other materials provided
 * with the distribution.
 * THIS SOFTWARE IS PROVIDED FREE OF CHARGE AND ON AN "AS IS" BASIS,
 * WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED INCLUDING
 * WITHOUT LIMITATION THE WARRANTIES THAT IT IS FREE OF DEFECTS, MERCHANTABLE,
 * FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK
 * AS TO THE QUALITY AND PERFORMANCE OF THE SOFTWARE IS WITH YOU.
 * SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL
 * NECESSARY SERVICING, REPAIR, OR CORRECTION.
 * IN NO EVENT SHALL ELCO SRL BE LIABLE TO YOU FOR DAMAGES, INCLUDING
 * ANY GENERAL, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING
 * OUT OF THE USE OR INABILITY TO USE THE SOFTWARE (INCLUDING, BUT NOT
 * LIMITED TO, LOSS OF DATA, DATA BEING RENDERED INACCURATE, LOSS OF
 * BUSINESS PROFITS, LOSS OF BUSINESS INFORMATION, BUSINESS INTERRUPTIONS,
 * LOSS SUSTAINED BY YOU OR THIRD PARTIES, OR A FAILURE OF THE SOFTWARE
 * TO OPERATE WITH ANY OTHER SOFTWARE) EVEN IF ELCO SRL HAS BEEN ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGES.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:00:12 PM CET 
//


package it.elco.xml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ProtocolloSAL"/>
 *         &lt;element ref="{}IdentificativoPiano"/>
 *         &lt;element ref="{}CodRegioneStrutturaPrescrittore"/>
 *         &lt;element ref="{}CodiceFiscalePrescrittore"/>
 *         &lt;element ref="{}CognomePrescrittore" minOccurs="0"/>
 *         &lt;element ref="{}NomePrescrittore" minOccurs="0"/>
 *         &lt;element ref="{}TelefonoPrescrittore" minOccurs="0"/>
 *         &lt;element ref="{}TipoErogatore"/>
 *         &lt;element ref="{}CodiceStruttura"/>
 *         &lt;element ref="{}Reparto" minOccurs="0"/>
 *         &lt;element ref="{}IndicazioneRinnovo"/>
 *         &lt;element ref="{}IdentificativoPianoPrecedente" minOccurs="0"/>
 *         &lt;element ref="{}DataPiano"/>
 *         &lt;element ref="{}DataRegistrazionePiano" minOccurs="0"/>
 *         &lt;element ref="{}DataScadenzaPiano" minOccurs="0"/>
 *         &lt;element ref="{}CodiceFiscaleAssistito"/>
 *         &lt;element ref="{}CognomeAssistito" minOccurs="0"/>
 *         &lt;element ref="{}NomeAssistito" minOccurs="0"/>
 *         &lt;element ref="{}DataNascitaAssistito"/>
 *         &lt;element ref="{}SessoAssistito"/>
 *         &lt;element ref="{}ComuneResidenzaAssistito" minOccurs="0"/>
 *         &lt;element ref="{}ProvinciaResidenzaAssistito" minOccurs="0"/>
 *         &lt;element ref="{}RegioneResidenzaAssistito" minOccurs="0"/>
 *         &lt;element ref="{}ASLResidenzaAssistito" minOccurs="0"/>
 *         &lt;element ref="{}CittadinanzaAssistito"/>
 *         &lt;element ref="{}StatoEsteroAssistito" minOccurs="0"/>
 *         &lt;element ref="{}PesoAssistito" minOccurs="0"/>
 *         &lt;element ref="{}AltezzaAssistito" minOccurs="0"/>
 *         &lt;element ref="{}NotaPrescrittore" minOccurs="0"/>
 *         &lt;element ref="{}EtaEsordioMalattia" minOccurs="0"/>
 *         &lt;element ref="{}MotivoCambioTerapia" minOccurs="0"/>
 *         &lt;element ref="{}CodMotivoCambioTerapia" minOccurs="0"/>
 *         &lt;element ref="{}Terapia1Linea" minOccurs="0"/>
 *         &lt;element ref="{}DatoAggiuntivo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}ModelloTF" maxOccurs="20"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "protocolloSAL",
    "identificativoPiano",
    "codRegioneStrutturaPrescrittore",
    "codiceFiscalePrescrittore",
    "cognomePrescrittore",
    "nomePrescrittore",
    "telefonoPrescrittore",
    "tipoErogatore",
    "codiceStruttura",
    "reparto",
    "indicazioneRinnovo",
    "identificativoPianoPrecedente",
    "dataPiano",
    "dataRegistrazionePiano",
    "dataScadenzaPiano",
    "codiceFiscaleAssistito",
    "cognomeAssistito",
    "nomeAssistito",
    "dataNascitaAssistito",
    "sessoAssistito",
    "comuneResidenzaAssistito",
    "provinciaResidenzaAssistito",
    "regioneResidenzaAssistito",
    "aslResidenzaAssistito",
    "cittadinanzaAssistito",
    "statoEsteroAssistito",
    "pesoAssistito",
    "altezzaAssistito",
    "notaPrescrittore",
    "etaEsordioMalattia",
    "motivoCambioTerapia",
    "codMotivoCambioTerapia",
    "terapia1Linea",
    "datoAggiuntivo",
    "modelloTF"
})
@XmlRootElement(name = "ModelloTBV")
public class ModelloTBV {

    @XmlElement(name = "ProtocolloSAL", required = true)
    protected BigInteger protocolloSAL;
    @XmlElement(name = "IdentificativoPiano", required = true)
    protected String identificativoPiano;
    @XmlElement(name = "CodRegioneStrutturaPrescrittore", required = true)
    protected String codRegioneStrutturaPrescrittore;
    @XmlElement(name = "CodiceFiscalePrescrittore", required = true)
    protected String codiceFiscalePrescrittore;
    @XmlElement(name = "CognomePrescrittore")
    protected String cognomePrescrittore;
    @XmlElement(name = "NomePrescrittore")
    protected String nomePrescrittore;
    @XmlElement(name = "TelefonoPrescrittore")
    protected String telefonoPrescrittore;
    @XmlElement(name = "TipoErogatore", required = true)
    protected String tipoErogatore;
    @XmlElement(name = "CodiceStruttura", required = true)
    protected String codiceStruttura;
    @XmlElement(name = "Reparto")
    protected String reparto;
    @XmlElement(name = "IndicazioneRinnovo", required = true)
    protected IndicazioneRinnovoType indicazioneRinnovo;
    @XmlElement(name = "IdentificativoPianoPrecedente")
    protected String identificativoPianoPrecedente;
    @XmlElement(name = "DataPiano", required = true)
    protected String dataPiano;
    @XmlElement(name = "DataRegistrazionePiano")
    protected String dataRegistrazionePiano;
    @XmlElement(name = "DataScadenzaPiano")
    protected String dataScadenzaPiano;
    @XmlElement(name = "CodiceFiscaleAssistito", required = true)
    protected String codiceFiscaleAssistito;
    @XmlElement(name = "CognomeAssistito")
    protected String cognomeAssistito;
    @XmlElement(name = "NomeAssistito")
    protected String nomeAssistito;
    @XmlElement(name = "DataNascitaAssistito", required = true)
    protected String dataNascitaAssistito;
    @XmlElement(name = "SessoAssistito", required = true)
    protected SessoType sessoAssistito;
    @XmlElement(name = "ComuneResidenzaAssistito")
    protected String comuneResidenzaAssistito;
    @XmlElement(name = "ProvinciaResidenzaAssistito")
    protected String provinciaResidenzaAssistito;
    @XmlElement(name = "RegioneResidenzaAssistito")
    protected String regioneResidenzaAssistito;
    @XmlElement(name = "ASLResidenzaAssistito")
    protected String aslResidenzaAssistito;
    @XmlElement(name = "CittadinanzaAssistito", required = true)
    protected String cittadinanzaAssistito;
    @XmlElement(name = "StatoEsteroAssistito")
    protected String statoEsteroAssistito;
    @XmlElement(name = "PesoAssistito")
    protected Integer pesoAssistito;
    @XmlElement(name = "AltezzaAssistito")
    protected Integer altezzaAssistito;
    @XmlElement(name = "NotaPrescrittore")
    protected String notaPrescrittore;
    @XmlElement(name = "EtaEsordioMalattia")
    protected Integer etaEsordioMalattia;
    @XmlElement(name = "MotivoCambioTerapia")
    protected String motivoCambioTerapia;
    @XmlElement(name = "CodMotivoCambioTerapia")
    protected String codMotivoCambioTerapia;
    @XmlElement(name = "Terapia1Linea")
    protected String terapia1Linea;
    @XmlElement(name = "DatoAggiuntivo")
    protected List<DatoAggiuntivo> datoAggiuntivo;
    @XmlElement(name = "ModelloTF", required = true)
    protected List<ModelloTF> modelloTF;

    /**
     * Gets the value of the protocolloSAL property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProtocolloSAL() {
        return protocolloSAL;
    }

    /**
     * Sets the value of the protocolloSAL property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProtocolloSAL(BigInteger value) {
        this.protocolloSAL = value;
    }

    /**
     * Gets the value of the identificativoPiano property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificativoPiano() {
        return identificativoPiano;
    }

    /**
     * Sets the value of the identificativoPiano property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificativoPiano(String value) {
        this.identificativoPiano = value;
    }

    /**
     * Gets the value of the codRegioneStrutturaPrescrittore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodRegioneStrutturaPrescrittore() {
        return codRegioneStrutturaPrescrittore;
    }

    /**
     * Sets the value of the codRegioneStrutturaPrescrittore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodRegioneStrutturaPrescrittore(String value) {
        this.codRegioneStrutturaPrescrittore = value;
    }

    /**
     * Gets the value of the codiceFiscalePrescrittore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscalePrescrittore() {
        return codiceFiscalePrescrittore;
    }

    /**
     * Sets the value of the codiceFiscalePrescrittore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscalePrescrittore(String value) {
        this.codiceFiscalePrescrittore = value;
    }

    /**
     * Gets the value of the cognomePrescrittore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCognomePrescrittore() {
        return cognomePrescrittore;
    }

    /**
     * Sets the value of the cognomePrescrittore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCognomePrescrittore(String value) {
        this.cognomePrescrittore = value;
    }

    /**
     * Gets the value of the nomePrescrittore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomePrescrittore() {
        return nomePrescrittore;
    }

    /**
     * Sets the value of the nomePrescrittore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomePrescrittore(String value) {
        this.nomePrescrittore = value;
    }

    /**
     * Gets the value of the telefonoPrescrittore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefonoPrescrittore() {
        return telefonoPrescrittore;
    }

    /**
     * Sets the value of the telefonoPrescrittore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefonoPrescrittore(String value) {
        this.telefonoPrescrittore = value;
    }

    /**
     * Gets the value of the tipoErogatore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoErogatore() {
        return tipoErogatore;
    }

    /**
     * Sets the value of the tipoErogatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoErogatore(String value) {
        this.tipoErogatore = value;
    }

    /**
     * Gets the value of the codiceStruttura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceStruttura() {
        return codiceStruttura;
    }

    /**
     * Sets the value of the codiceStruttura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceStruttura(String value) {
        this.codiceStruttura = value;
    }

    /**
     * Gets the value of the reparto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReparto() {
        return reparto;
    }

    /**
     * Sets the value of the reparto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReparto(String value) {
        this.reparto = value;
    }

    /**
     * Gets the value of the indicazioneRinnovo property.
     * 
     * @return
     *     possible object is
     *     {@link IndicazioneRinnovoType }
     *     
     */
    public IndicazioneRinnovoType getIndicazioneRinnovo() {
        return indicazioneRinnovo;
    }

    /**
     * Sets the value of the indicazioneRinnovo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndicazioneRinnovoType }
     *     
     */
    public void setIndicazioneRinnovo(IndicazioneRinnovoType value) {
        this.indicazioneRinnovo = value;
    }

    /**
     * Gets the value of the identificativoPianoPrecedente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificativoPianoPrecedente() {
        return identificativoPianoPrecedente;
    }

    /**
     * Sets the value of the identificativoPianoPrecedente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificativoPianoPrecedente(String value) {
        this.identificativoPianoPrecedente = value;
    }

    /**
     * Gets the value of the dataPiano property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataPiano() {
        return dataPiano;
    }

    /**
     * Sets the value of the dataPiano property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataPiano(String value) {
        this.dataPiano = value;
    }

    /**
     * Gets the value of the dataRegistrazionePiano property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRegistrazionePiano() {
        return dataRegistrazionePiano;
    }

    /**
     * Sets the value of the dataRegistrazionePiano property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRegistrazionePiano(String value) {
        this.dataRegistrazionePiano = value;
    }

    /**
     * Gets the value of the dataScadenzaPiano property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataScadenzaPiano() {
        return dataScadenzaPiano;
    }

    /**
     * Sets the value of the dataScadenzaPiano property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataScadenzaPiano(String value) {
        this.dataScadenzaPiano = value;
    }

    /**
     * Gets the value of the codiceFiscaleAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscaleAssistito() {
        return codiceFiscaleAssistito;
    }

    /**
     * Sets the value of the codiceFiscaleAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscaleAssistito(String value) {
        this.codiceFiscaleAssistito = value;
    }

    /**
     * Gets the value of the cognomeAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCognomeAssistito() {
        return cognomeAssistito;
    }

    /**
     * Sets the value of the cognomeAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCognomeAssistito(String value) {
        this.cognomeAssistito = value;
    }

    /**
     * Gets the value of the nomeAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeAssistito() {
        return nomeAssistito;
    }

    /**
     * Sets the value of the nomeAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeAssistito(String value) {
        this.nomeAssistito = value;
    }

    /**
     * Gets the value of the dataNascitaAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataNascitaAssistito() {
        return dataNascitaAssistito;
    }

    /**
     * Sets the value of the dataNascitaAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataNascitaAssistito(String value) {
        this.dataNascitaAssistito = value;
    }

    /**
     * Gets the value of the sessoAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link SessoType }
     *     
     */
    public SessoType getSessoAssistito() {
        return sessoAssistito;
    }

    /**
     * Sets the value of the sessoAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessoType }
     *     
     */
    public void setSessoAssistito(SessoType value) {
        this.sessoAssistito = value;
    }

    /**
     * Gets the value of the comuneResidenzaAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComuneResidenzaAssistito() {
        return comuneResidenzaAssistito;
    }

    /**
     * Sets the value of the comuneResidenzaAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComuneResidenzaAssistito(String value) {
        this.comuneResidenzaAssistito = value;
    }

    /**
     * Gets the value of the provinciaResidenzaAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinciaResidenzaAssistito() {
        return provinciaResidenzaAssistito;
    }

    /**
     * Sets the value of the provinciaResidenzaAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinciaResidenzaAssistito(String value) {
        this.provinciaResidenzaAssistito = value;
    }

    /**
     * Gets the value of the regioneResidenzaAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegioneResidenzaAssistito() {
        return regioneResidenzaAssistito;
    }

    /**
     * Sets the value of the regioneResidenzaAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegioneResidenzaAssistito(String value) {
        this.regioneResidenzaAssistito = value;
    }

    /**
     * Gets the value of the aslResidenzaAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getASLResidenzaAssistito() {
        return aslResidenzaAssistito;
    }

    /**
     * Sets the value of the aslResidenzaAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setASLResidenzaAssistito(String value) {
        this.aslResidenzaAssistito = value;
    }

    /**
     * Gets the value of the cittadinanzaAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCittadinanzaAssistito() {
        return cittadinanzaAssistito;
    }

    /**
     * Sets the value of the cittadinanzaAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCittadinanzaAssistito(String value) {
        this.cittadinanzaAssistito = value;
    }

    /**
     * Gets the value of the statoEsteroAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatoEsteroAssistito() {
        return statoEsteroAssistito;
    }

    /**
     * Sets the value of the statoEsteroAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatoEsteroAssistito(String value) {
        this.statoEsteroAssistito = value;
    }

    /**
     * Gets the value of the pesoAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPesoAssistito() {
        return pesoAssistito;
    }

    /**
     * Sets the value of the pesoAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPesoAssistito(Integer value) {
        this.pesoAssistito = value;
    }

    /**
     * Gets the value of the altezzaAssistito property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAltezzaAssistito() {
        return altezzaAssistito;
    }

    /**
     * Sets the value of the altezzaAssistito property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAltezzaAssistito(Integer value) {
        this.altezzaAssistito = value;
    }

    /**
     * Gets the value of the notaPrescrittore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotaPrescrittore() {
        return notaPrescrittore;
    }

    /**
     * Sets the value of the notaPrescrittore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotaPrescrittore(String value) {
        this.notaPrescrittore = value;
    }

    /**
     * Gets the value of the etaEsordioMalattia property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEtaEsordioMalattia() {
        return etaEsordioMalattia;
    }

    /**
     * Sets the value of the etaEsordioMalattia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEtaEsordioMalattia(Integer value) {
        this.etaEsordioMalattia = value;
    }

    /**
     * Gets the value of the motivoCambioTerapia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotivoCambioTerapia() {
        return motivoCambioTerapia;
    }

    /**
     * Sets the value of the motivoCambioTerapia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotivoCambioTerapia(String value) {
        this.motivoCambioTerapia = value;
    }

    /**
     * Gets the value of the codMotivoCambioTerapia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodMotivoCambioTerapia() {
        return codMotivoCambioTerapia;
    }

    /**
     * Sets the value of the codMotivoCambioTerapia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodMotivoCambioTerapia(String value) {
        this.codMotivoCambioTerapia = value;
    }

    /**
     * Gets the value of the terapia1Linea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerapia1Linea() {
        return terapia1Linea;
    }

    /**
     * Sets the value of the terapia1Linea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerapia1Linea(String value) {
        this.terapia1Linea = value;
    }

    /**
     * E' una stringa che contiene il valore e un attributo richiesto che definisce il suo nome
     * 
     * 			Gets the value of the datoAggiuntivo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datoAggiuntivo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatoAggiuntivo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatoAggiuntivo }
     * 
     * 
     */
    public List<DatoAggiuntivo> getDatoAggiuntivo() {
        if (datoAggiuntivo == null) {
            datoAggiuntivo = new ArrayList<DatoAggiuntivo>();
        }
        return this.datoAggiuntivo;
    }

    /**
     * Gets the value of the modelloTF property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelloTF property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelloTF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModelloTF }
     * 
     * 
     */
    public List<ModelloTF> getModelloTF() {
        if (modelloTF == null) {
            modelloTF = new ArrayList<ModelloTF>();
        }
        return this.modelloTF;
    }

}
