/* Copyright (c) 2018, EL.CO. SRL.  All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following
 * disclaimer in the documentation and/or other materials provided
 * with the distribution.
 * THIS SOFTWARE IS PROVIDED FREE OF CHARGE AND ON AN "AS IS" BASIS,
 * WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED INCLUDING
 * WITHOUT LIMITATION THE WARRANTIES THAT IT IS FREE OF DEFECTS, MERCHANTABLE,
 * FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK
 * AS TO THE QUALITY AND PERFORMANCE OF THE SOFTWARE IS WITH YOU.
 * SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL
 * NECESSARY SERVICING, REPAIR, OR CORRECTION.
 * IN NO EVENT SHALL ELCO SRL BE LIABLE TO YOU FOR DAMAGES, INCLUDING
 * ANY GENERAL, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING
 * OUT OF THE USE OR INABILITY TO USE THE SOFTWARE (INCLUDING, BUT NOT
 * LIMITED TO, LOSS OF DATA, DATA BEING RENDERED INACCURATE, LOSS OF
 * BUSINESS PROFITS, LOSS OF BUSINESS INFORMATION, BUSINESS INTERRUPTIONS,
 * LOSS SUSTAINED BY YOU OR THIRD PARTIES, OR A FAILURE OF THE SOFTWARE
 * TO OPERATE WITH ANY OTHER SOFTWARE) EVEN IF ELCO SRL HAS BEEN ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGES.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:00:12 PM CET 
//


package it.elco.xml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CodiceTerapia"/>
 *         &lt;element ref="{}Unita"/>
 *         &lt;element ref="{}PeriodoSomministrazione"/>
 *         &lt;element ref="{}DurataTrattamento"/>
 *         &lt;element ref="{}NumeroLitri" minOccurs="0"/>
 *         &lt;element ref="{}NumeroOre" minOccurs="0"/>
 *         &lt;element ref="{}DatoAggiuntivo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codiceTerapia",
    "unita",
    "periodoSomministrazione",
    "durataTrattamento",
    "numeroLitri",
    "numeroOre",
    "datoAggiuntivo"
})
@XmlRootElement(name = "ModelloTF")
public class ModelloTF {

    @XmlElement(name = "CodiceTerapia", required = true)
    protected String codiceTerapia;
    @XmlElement(name = "Unita", required = true)
    protected String unita;
    @XmlElement(name = "PeriodoSomministrazione", required = true)
    protected PeriodoSomministrazioneType periodoSomministrazione;
    @XmlElement(name = "DurataTrattamento")
    protected int durataTrattamento;
    @XmlElement(name = "NumeroLitri")
    protected Integer numeroLitri;
    @XmlElement(name = "NumeroOre")
    protected BigDecimal numeroOre;
    @XmlElement(name = "DatoAggiuntivo")
    protected List<DatoAggiuntivo> datoAggiuntivo;

    /**
     * Gets the value of the codiceTerapia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceTerapia() {
        return codiceTerapia;
    }

    /**
     * Sets the value of the codiceTerapia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceTerapia(String value) {
        this.codiceTerapia = value;
    }

    /**
     * Gets the value of the unita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnita() {
        return unita;
    }

    /**
     * Sets the value of the unita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnita(String value) {
        this.unita = value;
    }

    /**
     * Gets the value of the periodoSomministrazione property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodoSomministrazioneType }
     *     
     */
    public PeriodoSomministrazioneType getPeriodoSomministrazione() {
        return periodoSomministrazione;
    }

    /**
     * Sets the value of the periodoSomministrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodoSomministrazioneType }
     *     
     */
    public void setPeriodoSomministrazione(PeriodoSomministrazioneType value) {
        this.periodoSomministrazione = value;
    }

    /**
     * Gets the value of the durataTrattamento property.
     * 
     */
    public int getDurataTrattamento() {
        return durataTrattamento;
    }

    /**
     * Sets the value of the durataTrattamento property.
     * 
     */
    public void setDurataTrattamento(int value) {
        this.durataTrattamento = value;
    }

    /**
     * Gets the value of the numeroLitri property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumeroLitri() {
        return numeroLitri;
    }

    /**
     * Sets the value of the numeroLitri property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumeroLitri(Integer value) {
        this.numeroLitri = value;
    }

    /**
     * Gets the value of the numeroOre property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumeroOre() {
        return numeroOre;
    }

    /**
     * Sets the value of the numeroOre property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumeroOre(BigDecimal value) {
        this.numeroOre = value;
    }

    /**
     * E' una stringa che contiene il valore e un attributo richiesto che definisce il suo nome
     * 
     * 			Gets the value of the datoAggiuntivo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datoAggiuntivo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatoAggiuntivo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatoAggiuntivo }
     * 
     * 
     */
    public List<DatoAggiuntivo> getDatoAggiuntivo() {
        if (datoAggiuntivo == null) {
            datoAggiuntivo = new ArrayList<DatoAggiuntivo>();
        }
        return this.datoAggiuntivo;
    }

}
