/* Copyright (c) 2018, EL.CO. SRL.  All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following
 * disclaimer in the documentation and/or other materials provided
 * with the distribution.
 * THIS SOFTWARE IS PROVIDED FREE OF CHARGE AND ON AN "AS IS" BASIS,
 * WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED INCLUDING
 * WITHOUT LIMITATION THE WARRANTIES THAT IT IS FREE OF DEFECTS, MERCHANTABLE,
 * FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK
 * AS TO THE QUALITY AND PERFORMANCE OF THE SOFTWARE IS WITH YOU.
 * SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL
 * NECESSARY SERVICING, REPAIR, OR CORRECTION.
 * IN NO EVENT SHALL ELCO SRL BE LIABLE TO YOU FOR DAMAGES, INCLUDING
 * ANY GENERAL, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING
 * OUT OF THE USE OR INABILITY TO USE THE SOFTWARE (INCLUDING, BUT NOT
 * LIMITED TO, LOSS OF DATA, DATA BEING RENDERED INACCURATE, LOSS OF
 * BUSINESS PROFITS, LOSS OF BUSINESS INFORMATION, BUSINESS INTERRUPTIONS,
 * LOSS SUSTAINED BY YOU OR THIRD PARTIES, OR A FAILURE OF THE SOFTWARE
 * TO OPERATE WITH ANY OTHER SOFTWARE) EVEN IF ELCO SRL HAS BEEN ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGES.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:00:12 PM CET 
//


package it.elco.xml;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.elco.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PinCode_QNAME = new QName("", "PinCode");
    private final static QName _PesoAssistito_QNAME = new QName("", "PesoAssistito");
    private final static QName _DataPiano_QNAME = new QName("", "DataPiano");
    private final static QName _DurataTrattamento_QNAME = new QName("", "DurataTrattamento");
    private final static QName _Testata1_QNAME = new QName("", "Testata1");
    private final static QName _NumeroLitri_QNAME = new QName("", "NumeroLitri");
    private final static QName _Testata2_QNAME = new QName("", "Testata2");
    private final static QName _IdentificativoPianoPrecedente_QNAME = new QName("", "IdentificativoPianoPrecedente");
    private final static QName _DataRegistrazionePiano_QNAME = new QName("", "DataRegistrazionePiano");
    private final static QName _NomePrescrittore_QNAME = new QName("", "NomePrescrittore");
    private final static QName _NomeAssistito_QNAME = new QName("", "NomeAssistito");
    private final static QName _CodiceFiscaleAssistito_QNAME = new QName("", "CodiceFiscaleAssistito");
    private final static QName _CodRegioneStrutturaPrescrittore_QNAME = new QName("", "CodRegioneStrutturaPrescrittore");
    private final static QName _DataNascitaAssistito_QNAME = new QName("", "DataNascitaAssistito");
    private final static QName _DataScadenzaPiano_QNAME = new QName("", "DataScadenzaPiano");
    private final static QName _CognomeAssistito_QNAME = new QName("", "CognomeAssistito");
    private final static QName _CognomePrescrittore_QNAME = new QName("", "CognomePrescrittore");
    private final static QName _Unita_QNAME = new QName("", "Unita");
    private final static QName _AltezzaAssistito_QNAME = new QName("", "AltezzaAssistito");
    private final static QName _ComuneResidenzaAssistito_QNAME = new QName("", "ComuneResidenzaAssistito");
    private final static QName _NotaPrescrittore_QNAME = new QName("", "NotaPrescrittore");
    private final static QName _EtaEsordioMalattia_QNAME = new QName("", "EtaEsordioMalattia");
    private final static QName _SessoAssistito_QNAME = new QName("", "SessoAssistito");
    private final static QName _TipoInvio_QNAME = new QName("", "TipoInvio");
    private final static QName _RegioneResidenzaAssistito_QNAME = new QName("", "RegioneResidenzaAssistito");
    private final static QName _StatoEsteroAssistito_QNAME = new QName("", "StatoEsteroAssistito");
    private final static QName _CodMotivoCambioTerapia_QNAME = new QName("", "CodMotivoCambioTerapia");
    private final static QName _TipoErogatore_QNAME = new QName("", "TipoErogatore");
    private final static QName _ASLResidenzaAssistito_QNAME = new QName("", "ASLResidenzaAssistito");
    private final static QName _IdentificativoPiano_QNAME = new QName("", "IdentificativoPiano");
    private final static QName _CittadinanzaAssistito_QNAME = new QName("", "CittadinanzaAssistito");
    private final static QName _PeriodoSomministrazione_QNAME = new QName("", "PeriodoSomministrazione");
    private final static QName _ProvinciaResidenzaAssistito_QNAME = new QName("", "ProvinciaResidenzaAssistito");
    private final static QName _CodiceTerapia_QNAME = new QName("", "CodiceTerapia");
    private final static QName _ProtocolloSAL_QNAME = new QName("", "ProtocolloSAL");
    private final static QName _NumeroOre_QNAME = new QName("", "NumeroOre");
    private final static QName _Reparto_QNAME = new QName("", "Reparto");
    private final static QName _MotivoCambioTerapia_QNAME = new QName("", "MotivoCambioTerapia");
    private final static QName _CodiceStruttura_QNAME = new QName("", "CodiceStruttura");
    private final static QName _TelefonoPrescrittore_QNAME = new QName("", "TelefonoPrescrittore");
    private final static QName _Terapia1Linea_QNAME = new QName("", "Terapia1Linea");
    private final static QName _CodiceFiscalePrescrittore_QNAME = new QName("", "CodiceFiscalePrescrittore");
    private final static QName _IndicazioneRinnovo_QNAME = new QName("", "IndicazioneRinnovo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.elco.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Testata }
     * 
     */
    public Testata createTestata() {
        return new Testata();
    }

    /**
     * Create an instance of {@link ModelloTBV }
     * 
     */
    public ModelloTBV createModelloTBV() {
        return new ModelloTBV();
    }

    /**
     * Create an instance of {@link PianiTerapeutici }
     * 
     */
    public PianiTerapeutici createPianiTerapeutici() {
        return new PianiTerapeutici();
    }

    /**
     * Create an instance of {@link DatoAggiuntivo }
     * 
     */
    public DatoAggiuntivo createDatoAggiuntivo() {
        return new DatoAggiuntivo();
    }

    /**
     * Create an instance of {@link ModelloTBI }
     * 
     */
    public ModelloTBI createModelloTBI() {
        return new ModelloTBI();
    }

    /**
     * Create an instance of {@link ModelloTF }
     * 
     */
    public ModelloTF createModelloTF() {
        return new ModelloTF();
    }

    /**
     * Create an instance of {@link ModelloTBC }
     * 
     */
    public ModelloTBC createModelloTBC() {
        return new ModelloTBC();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PinCode")
    public JAXBElement<String> createPinCode(String value) {
        return new JAXBElement<String>(_PinCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PesoAssistito")
    public JAXBElement<Integer> createPesoAssistito(Integer value) {
        return new JAXBElement<Integer>(_PesoAssistito_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataPiano")
    public JAXBElement<String> createDataPiano(String value) {
        return new JAXBElement<String>(_DataPiano_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DurataTrattamento")
    public JAXBElement<Integer> createDurataTrattamento(Integer value) {
        return new JAXBElement<Integer>(_DurataTrattamento_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Testata1")
    public JAXBElement<String> createTestata1(String value) {
        return new JAXBElement<String>(_Testata1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NumeroLitri")
    public JAXBElement<Integer> createNumeroLitri(Integer value) {
        return new JAXBElement<Integer>(_NumeroLitri_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Testata2")
    public JAXBElement<String> createTestata2(String value) {
        return new JAXBElement<String>(_Testata2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IdentificativoPianoPrecedente")
    public JAXBElement<String> createIdentificativoPianoPrecedente(String value) {
        return new JAXBElement<String>(_IdentificativoPianoPrecedente_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataRegistrazionePiano")
    public JAXBElement<String> createDataRegistrazionePiano(String value) {
        return new JAXBElement<String>(_DataRegistrazionePiano_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NomePrescrittore")
    public JAXBElement<String> createNomePrescrittore(String value) {
        return new JAXBElement<String>(_NomePrescrittore_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NomeAssistito")
    public JAXBElement<String> createNomeAssistito(String value) {
        return new JAXBElement<String>(_NomeAssistito_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodiceFiscaleAssistito")
    public JAXBElement<String> createCodiceFiscaleAssistito(String value) {
        return new JAXBElement<String>(_CodiceFiscaleAssistito_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodRegioneStrutturaPrescrittore")
    public JAXBElement<String> createCodRegioneStrutturaPrescrittore(String value) {
        return new JAXBElement<String>(_CodRegioneStrutturaPrescrittore_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataNascitaAssistito")
    public JAXBElement<String> createDataNascitaAssistito(String value) {
        return new JAXBElement<String>(_DataNascitaAssistito_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataScadenzaPiano")
    public JAXBElement<String> createDataScadenzaPiano(String value) {
        return new JAXBElement<String>(_DataScadenzaPiano_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CognomeAssistito")
    public JAXBElement<String> createCognomeAssistito(String value) {
        return new JAXBElement<String>(_CognomeAssistito_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CognomePrescrittore")
    public JAXBElement<String> createCognomePrescrittore(String value) {
        return new JAXBElement<String>(_CognomePrescrittore_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Unita")
    public JAXBElement<String> createUnita(String value) {
        return new JAXBElement<String>(_Unita_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AltezzaAssistito")
    public JAXBElement<Integer> createAltezzaAssistito(Integer value) {
        return new JAXBElement<Integer>(_AltezzaAssistito_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ComuneResidenzaAssistito")
    public JAXBElement<String> createComuneResidenzaAssistito(String value) {
        return new JAXBElement<String>(_ComuneResidenzaAssistito_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NotaPrescrittore")
    public JAXBElement<String> createNotaPrescrittore(String value) {
        return new JAXBElement<String>(_NotaPrescrittore_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EtaEsordioMalattia")
    public JAXBElement<Integer> createEtaEsordioMalattia(Integer value) {
        return new JAXBElement<Integer>(_EtaEsordioMalattia_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SessoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SessoAssistito")
    public JAXBElement<SessoType> createSessoAssistito(SessoType value) {
        return new JAXBElement<SessoType>(_SessoAssistito_QNAME, SessoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TipoInvioType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TipoInvio")
    public JAXBElement<TipoInvioType> createTipoInvio(TipoInvioType value) {
        return new JAXBElement<TipoInvioType>(_TipoInvio_QNAME, TipoInvioType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RegioneResidenzaAssistito")
    public JAXBElement<String> createRegioneResidenzaAssistito(String value) {
        return new JAXBElement<String>(_RegioneResidenzaAssistito_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StatoEsteroAssistito")
    public JAXBElement<String> createStatoEsteroAssistito(String value) {
        return new JAXBElement<String>(_StatoEsteroAssistito_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodMotivoCambioTerapia")
    public JAXBElement<String> createCodMotivoCambioTerapia(String value) {
        return new JAXBElement<String>(_CodMotivoCambioTerapia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TipoErogatore")
    public JAXBElement<String> createTipoErogatore(String value) {
        return new JAXBElement<String>(_TipoErogatore_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ASLResidenzaAssistito")
    public JAXBElement<String> createASLResidenzaAssistito(String value) {
        return new JAXBElement<String>(_ASLResidenzaAssistito_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IdentificativoPiano")
    public JAXBElement<String> createIdentificativoPiano(String value) {
        return new JAXBElement<String>(_IdentificativoPiano_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CittadinanzaAssistito")
    public JAXBElement<String> createCittadinanzaAssistito(String value) {
        return new JAXBElement<String>(_CittadinanzaAssistito_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PeriodoSomministrazioneType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PeriodoSomministrazione")
    public JAXBElement<PeriodoSomministrazioneType> createPeriodoSomministrazione(PeriodoSomministrazioneType value) {
        return new JAXBElement<PeriodoSomministrazioneType>(_PeriodoSomministrazione_QNAME, PeriodoSomministrazioneType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProvinciaResidenzaAssistito")
    public JAXBElement<String> createProvinciaResidenzaAssistito(String value) {
        return new JAXBElement<String>(_ProvinciaResidenzaAssistito_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodiceTerapia")
    public JAXBElement<String> createCodiceTerapia(String value) {
        return new JAXBElement<String>(_CodiceTerapia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProtocolloSAL")
    public JAXBElement<BigInteger> createProtocolloSAL(BigInteger value) {
        return new JAXBElement<BigInteger>(_ProtocolloSAL_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NumeroOre")
    public JAXBElement<BigDecimal> createNumeroOre(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NumeroOre_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reparto")
    public JAXBElement<String> createReparto(String value) {
        return new JAXBElement<String>(_Reparto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MotivoCambioTerapia")
    public JAXBElement<String> createMotivoCambioTerapia(String value) {
        return new JAXBElement<String>(_MotivoCambioTerapia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodiceStruttura")
    public JAXBElement<String> createCodiceStruttura(String value) {
        return new JAXBElement<String>(_CodiceStruttura_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TelefonoPrescrittore")
    public JAXBElement<String> createTelefonoPrescrittore(String value) {
        return new JAXBElement<String>(_TelefonoPrescrittore_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Terapia1Linea")
    public JAXBElement<String> createTerapia1Linea(String value) {
        return new JAXBElement<String>(_Terapia1Linea_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodiceFiscalePrescrittore")
    public JAXBElement<String> createCodiceFiscalePrescrittore(String value) {
        return new JAXBElement<String>(_CodiceFiscalePrescrittore_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IndicazioneRinnovoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IndicazioneRinnovo")
    public JAXBElement<IndicazioneRinnovoType> createIndicazioneRinnovo(IndicazioneRinnovoType value) {
        return new JAXBElement<IndicazioneRinnovoType>(_IndicazioneRinnovo_QNAME, IndicazioneRinnovoType.class, null, value);
    }

}
