/* Copyright (c) 2018, EL.CO. SRL.  All rights reserved.
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following
 * disclaimer in the documentation and/or other materials provided
 * with the distribution.
 * THIS SOFTWARE IS PROVIDED FREE OF CHARGE AND ON AN "AS IS" BASIS,
 * WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED INCLUDING
 * WITHOUT LIMITATION THE WARRANTIES THAT IT IS FREE OF DEFECTS, MERCHANTABLE,
 * FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING. THE ENTIRE RISK
 * AS TO THE QUALITY AND PERFORMANCE OF THE SOFTWARE IS WITH YOU.
 * SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL
 * NECESSARY SERVICING, REPAIR, OR CORRECTION.
 * IN NO EVENT SHALL ELCO SRL BE LIABLE TO YOU FOR DAMAGES, INCLUDING
 * ANY GENERAL, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING
 * OUT OF THE USE OR INABILITY TO USE THE SOFTWARE (INCLUDING, BUT NOT
 * LIMITED TO, LOSS OF DATA, DATA BEING RENDERED INACCURATE, LOSS OF
 * BUSINESS PROFITS, LOSS OF BUSINESS INFORMATION, BUSINESS INTERRUPTIONS,
 * LOSS SUSTAINED BY YOU OR THIRD PARTIES, OR A FAILURE OF THE SOFTWARE
 * TO OPERATE WITH ANY OTHER SOFTWARE) EVEN IF ELCO SRL HAS BEEN ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGES.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 12:00:12 PM CET 
//


package it.elco.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Testata"/>
 *         &lt;choice maxOccurs="5000">
 *           &lt;element ref="{}ModelloTBI"/>
 *           &lt;element ref="{}ModelloTBV"/>
 *           &lt;element ref="{}ModelloTBC"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testata",
    "modelloTBIOrModelloTBVOrModelloTBC"
})
@XmlRootElement(name = "PianiTerapeutici")
public class PianiTerapeutici {

    @XmlElement(name = "Testata", required = true)
    protected Testata testata;
    @XmlElements({
        @XmlElement(name = "ModelloTBC", type = ModelloTBC.class),
        @XmlElement(name = "ModelloTBV", type = ModelloTBV.class),
        @XmlElement(name = "ModelloTBI", type = ModelloTBI.class)
    })
    protected List<Object> modelloTBIOrModelloTBVOrModelloTBC;

    /**
     * 
     * 
     * Elemento strutturale che comprende solo i dati comuni a tutti
     * 
     * i piani indicati in seguito
     * 
     * 
     * 
     * @return
     *     possible object is
     *     {@link Testata }
     *     
     */
    public Testata getTestata() {
        return testata;
    }

    /**
     * Sets the value of the testata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testata }
     *     
     */
    public void setTestata(Testata value) {
        this.testata = value;
    }

    /**
     * Gets the value of the modelloTBIOrModelloTBVOrModelloTBC property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelloTBIOrModelloTBVOrModelloTBC property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelloTBIOrModelloTBVOrModelloTBC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModelloTBC }
     * {@link ModelloTBV }
     * {@link ModelloTBI }
     * 
     * 
     */
    public List<Object> getModelloTBIOrModelloTBVOrModelloTBC() {
        if (modelloTBIOrModelloTBVOrModelloTBC == null) {
            modelloTBIOrModelloTBVOrModelloTBC = new ArrayList<Object>();
        }
        return this.modelloTBIOrModelloTBVOrModelloTBC;
    }

}
