

var IP_MIDDLEWARE_PRESCRIZIONE="http://10.106.128.181"; 
var IP_MIDDLEWARE_EROGAZIONE="http://10.106.0.129"; 

var DEMA_PRESCRIZIONE_SAVONA = {
	// dreprecati
    CODICE_AZIENDA_PRENOTATORE : "102",
    CODICE_REGIONE_PRENOTATORE : "070",
	//CODICE_STRUTTURA : "999910",
	// produzione
    URL_MIDDLEWARE:IP_MIDDLEWARE_PRESCRIZIONE + ":9666/SD"
};


var DEMA_ANNULLA_SAVONA = {
    URL_MIDDLEWARE:IP_MIDDLEWARE_PRESCRIZIONE + ":9666/ANNULLABLOCCO"
};


var DEMA_SAVONA = {
	// produzione
	URL_MIDDLEWARE:IP_MIDDLEWARE_EROGAZIONE + ":9699/BLOCCA"  
};


var EASYCUP_SERVICES = {
	URL_WEB:"http://192.168.4.140:8887/easycup/sso?",
	//URL_WEB:"http://192.168.104.30:8190/easycup/sso?",
    URL_MIDDLEWARE:IP_MIDDLEWARE_EROGAZIONE+":7001/EASYCup",
    applicationname:"ONESYS",
    key:"y65g7t"
    //  key:"123456"
};

var SATAPP_SERVICES = {
    CODICE_AZIENDA_PRENOTATORE : "109",
    CODICE_REGIONE_PRENOTATORE : "080",
    URL_MIDDLEWARE:IP_MIDDLEWARE_EROGAZIONE+":7001/SATAPP"
};


var SARPED_SERVICES = {
     URL_MIDDLEWARE:IP_MIDDLEWARE_EROGAZIONE+":7001/SARPED"  
};

var SIRD_SERVICES = {
    URL_MIDDLEWARE:IP_MIDDLEWARE_EROGAZIONE+":7001/SIRD"
};

var RICETTA_SERVICES = {
    URL_RISTAMPA:IP_MIDDLEWARE_EROGAZIONE+":7001/RISTAMPA_PROMEMORIA",
    URL_PRESTAZIONI:IP_MIDDLEWARE_EROGAZIONE+":18080/servizi/SATPED/prescrizionePrestazioni",
    URL_SATPED:IP_MIDDLEWARE_EROGAZIONE+":18080/servizi/SATPED/",
    URL_INFORMATIZZATA:IP_MIDDLEWARE_EROGAZIONE+":18080/servizi/",
    URL_SAASPED:IP_MIDDLEWARE_EROGAZIONE+":18080/servizi/SAASPED/annullamentoPrescrizioni",
    URL_SAAPEF:IP_MIDDLEWARE_EROGAZIONE+":7001/SAAPEF"
};

var REMOTE_SEARCH = {
    URL_MIDDLEWARE:IP_MIDDLEWARE_EROGAZIONE+":7001/RR-FARMACI"
};